Syslog          yes
UMask           002
Socket          inet:8891@localhost
PidFile         /var/run/opendkim.pid
OversignHeaders From
TrustAnchorFile /usr/share/dns/root.key
UserID          opendkim:opendkim
